# fly.toml app configuration file generated for crossword-0drx8a on 2026-09-21T17:25:36Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'crossword-0drx8a'
primary_region = 'iad'

[build]
  dockerfile = 'server/Dockerfile'

[http_service]
  internal_port = 8787
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
